name: Build and Deploy WebAssembly App

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Emscripten Toolchain
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 'latest'

    - name: Compile C++ to WebAssembly
      run: |
        mkdir -p dist
        emcc src/*.cpp -o dist/index.html -s USE_GLFW=3 -s FULL_ES3=1 -DSHADER_DIR='"Shaders/"' --preload-file Shaders

    - name: Push Build to GitHub Pages Branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
        branch: gh-pages
